// URL scan + auto .md generator
// Fetch a page, scan text content, generate a diff-style .md report for the dev team.

const { net } = require('electron');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { scanText } = require('../engine/scanner');
const { localRewrite } = require('../engine/rewriter');

function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    const req = net.request(url);
    let body = '';
    req.on('response', (res) => {
      res.on('data', (chunk) => { body += chunk.toString(); });
      res.on('end', () => resolve(body));
    });
    req.on('error', reject);
    req.end();
  });
}

function htmlToText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();
}

async function scanUrlGenerateMd(url, options = {}) {
  if (!/^https?:\/\//i.test(url)) url = 'https://' + url;

  const html = await fetchUrl(url);
  const text = htmlToText(html);
  const scan = scanText(text);
  const rewrite = localRewrite(text);
  const scanAfter = scanText(rewrite.text);

  const md = buildMd(url, text, scan, rewrite, scanAfter);

  // Save to a temp location by default, or options.outPath
  const outPath = options.outPath || path.join(
    os.tmpdir(),
    `slop-report-${new URL(url).hostname.replace(/\./g, '-')}-${Date.now()}.md`
  );
  fs.writeFileSync(outPath, md);

  return {
    url,
    score: scan.score,
    scoreAfter: scanAfter.score,
    issueCount: scan.issues.length,
    changesApplied: rewrite.changeCount,
    outPath,
    markdown: md,
  };
}

function buildMd(url, text, scan, rewrite, scanAfter) {
  const lines = [
    `# Slop Report: ${url}`,
    '',
    `**Generated:** ${new Date().toISOString()}`,
    `**Slop score (before):** ${scan.score}/100`,
    `**Slop score (after):** ${scanAfter.score}/100`,
    `**Issues found:** ${scan.issues.length} (High: ${scan.highCount}, Medium: ${scan.medCount}, Low: ${scan.lowCount})`,
    `**Changes suggested:** ${rewrite.changeCount}`,
    '',
    '## Suggested Fixes',
    '',
    '| Before | After |',
    '|--------|-------|',
    ...rewrite.changes.slice(0, 50).map(c =>
      `| ${escapeCell(c.from)} | ${escapeCell(c.to) || '(removed)'} |`
    ),
    '',
    '## Full Issue List',
    '',
    '| Category | Severity | Match |',
    '|----------|----------|-------|',
    ...scan.issues.slice(0, 100).map(i =>
      `| ${i.category} | ${i.severity} | ${escapeCell(i.match)} |`
    ),
    '',
    '---',
    '*Generated by Prompt Sweeper / Slop Hog*',
  ];
  return lines.join('\n') + '\n';
}

function escapeCell(s) {
  return String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ').slice(0, 200);
}

module.exports = { scanUrlGenerateMd };
